backend:
  name: test-repo
  repo: jason86trainer/Nature2life-luxury-preview
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "data/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "homepage"
    label: "Homepage"
    files:
      - file: "data/homepage.json"
        label: "Homepage Content"
        name: "homepage"
        fields:
          - { label: "Hero Title", name: "heroTitle", widget: "string" }
          - { label: "Hero Subtitle", name: "heroSubtitle", widget: "text" }

  - name: "markets"
    label: "Markets"
    files:
      - file: "data/markets.json"
        label: "Markets"
        name: "markets"
        fields:
          - { label: "Next Market Date", name: "nextDate", widget: "datetime" }
          - { label: "Location", name: "location", widget: "string" }
